apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: elasticsearch
    spec:
      containers:
    #  - args:
     #   - elasticsearch
      #  - -Des.cluster.name=graylog
      - image: eldhodoc/elasticsearch
        name: elasticsearch
        resources: {}
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticvol
      volumes:
       - name: elasticvol
         emptyDir: {}
      restartPolicy: Always

