apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: graylog
  name: graylog
spec:
  type: NodePort
  ports:
  - name: "9000"
    port: 80
    targetPort: 9000
    nodePort: 32328
  - name: "12201"
    port: 12201
    targetPort: 12201
 # - name: "514"
  #  port: 514
   # targetPort: 514
   # protocol: UDP
  #externalIPs:
  #- 10.15.0.96
  #clusterIP: None
  selector:
    service: graylog