apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: graylog
  name: graylogsrv
spec:
  #type: NodePort
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    #nodePort: 32328
  - name: "12201"
    port: 12201
    targetPort: 12201
  clusterIP: None
  selector:
    service: graylog