apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: graylog
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graylog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: graylog
    spec:
      containers:
      - command:
        - /usr/bin/tini
        - --
        - wait-for-it
        - elasticsearch:9200
        - --
        - /docker-entrypoint.sh
        env:
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://127.0.0.1:9000/
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://127.0.0.1:9000/api
        image: graylog/graylog:4.2
        imagePullPolicy: ""
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 1514
        - containerPort: 1514
          protocol: UDP
        - containerPort: 12201
        - containerPort: 12201
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/graylog/data
          name: graylog-graylog-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: graylog-graylog-data
        persistentVolumeClaim:
          claimName: graylog-graylog-data
status: {}
